---
title: "Weight analyses"
output: html_notebook
---
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(lme4)
library(boot)
```

```{r}
num_layers = 5
entropy_data = read.csv('./results_all_layers/entropies.csv', header=T)
contrasts(entropy_data$type) = cbind(linear_post=c(1, 0, 0, 0), post=c(0, 1, 0, 0), pre=c(0, 0, 1, 0)) # make random the reference
```
 
```{r}
theme_set(theme_bw() +
            theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank()))
```

```{r}
for (this_layer in 0:(num_layers-1)) {
  ggplot(data=entropy_data %>% filter(layer==this_layer), aes(x=entropy, color=type))  +
    scale_color_brewer(palette="Dark2") +
    geom_density(size=1.2) +
    facet_grid(mode_type ~ .)
  ggsave(sprintf("plots/modes_entropy_density_layer_%i.png", this_layer), width=7, height=14)
   
  ggplot(data=entropy_data %>% filter(mode_rank < 30, layer==this_layer), aes(x=entropy, color=type))  +
    scale_color_brewer(palette="Dark2") +
    geom_density(size=1.2) +
    facet_grid(mode_type ~ .)
  ggsave(sprintf("plots/high_rank_modes_entropy_density_layer_%i.png", this_layer), width=7, height=14)
}
```

```{r}
#res = lmer(entropy ~ type + (1|run), data=entropy_data)
#summary(res)
```

```{r}
# coefficient_getter = function(data, indices) {
#   res = lmer(entropy ~ type + (1|run), data=data[indices,])
#   res = summary(res)
#   linear_b = res$coefficients[2, 1]
#   post_b = res$coefficients[3, 1]
#   pre_b = res$coefficients[4, 1]
#   tanh_b = res$coefficients[5, 1]
#   return(c(pre_b, post_b, linear_b, tanh_b))
# }

```

```{r}
# bootstrap_results = boot(data=entropy_data, statistic=coefficient_getter, R=5000)
```

```{r}
# boot.ci(bootstrap_results, type="perc", index=1)
# boot.ci(bootstrap_results, type="perc", index=2, conf=0.999)
# boot.ci(bootstrap_results, type="perc", index=3)
# boot.ci(bootstrap_results, type="perc", index=4)
```

# correlation of rank with entropy

```{r}
entropy_correlation_data = entropy_data %>%
  filter(mode_rank < 50, grepl("output", mode_type)) %>%
  group_by(type, layer, mode_rank) %>%
  summarize(mean_entropy=mean(entropy), mean_strength=mean(as.numeric(mode_strength)))
```

```{r}
ggplot(entropy_correlation_data,
       aes(x=mode_rank, y=mean_entropy, color=type)) +
  geom_point() +
  geom_line() +
  scale_color_brewer(palette="Dark2") +
  facet_wrap(~layer)
```


```{r}
ggplot(entropy_correlation_data %>%
         filter(type != " tanh_post"), # hard to interpret raw strengths across non-linearities
       aes(x=mean_strength, y=mean_entropy, color=type)) +
  geom_point() +
  geom_line() +
  scale_color_brewer(palette="Dark2") +
  facet_wrap(~layer)
```